package config;

import java.awt.Font;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.zip.GZIPOutputStream;
import org.json.simple.JSONObject;

public class FeedbackView extends javax.swing.JPanel {

	SettingsController controller;

	public FeedbackView () {
		initComponents ();
		this.setFont (new Font ("Monospaced", Font.PLAIN, 15));
	}

	public void setController (SettingsController configController) {
		this.controller = configController;
		this.settingsPanel.setController (configController);
	}
	
	public JSONObject getSttings () {
		return this.settingsPanel.getSttings ();
	}
	
	public void setSettings (JSONObject settings) {
		this.settingsPanel.setSettings (settings);
	}
	

	public void println (String s) {
		feedbackPanel.setText (feedbackPanel.getText () + "\n" + s);
		feedbackPanel.setCaretPosition (feedbackPanel.getDocument ().getLength ());
	}

	public void clear () {
		feedbackPanel.setText ("");
		feedbackPanel.setContentType ("text/plain");//set content as html
	}

	public String getFeedbackText () {
		String feedBack = "COMMENTS:\n" + this.commentsText.getText () + "\n";
		feedBack = "MESSAGES:\n" + feedbackPanel.getText ();
		return feedBack;
	}

	public byte[] getFeedbackCompressedBytes () {
		String text = feedbackPanel.getText ();
		byte[] bytes = text.getBytes (StandardCharsets.UTF_8);
		ByteArrayOutputStream outputStream = new ByteArrayOutputStream ();
		try (GZIPOutputStream gzipOutputStream = new GZIPOutputStream (outputStream)) {
			gzipOutputStream.write (bytes);
		} catch (IOException e) {
			e.printStackTrace ();
		}

		byte[] compressedBytes = outputStream.toByteArray ();
		return (compressedBytes);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    commentsPanel = new javax.swing.JPanel();
    commentsScroll = new javax.swing.JScrollPane();
    commentsText = new javax.swing.JTextArea();
    commentsButton = new javax.swing.JButton();
    messagesScroll = new javax.swing.JScrollPane();
    feedbackPanel = new javax.swing.JEditorPane();
    settingsPanel = new config.SettingsPanel();

    setLayout(new java.awt.BorderLayout());

    commentsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escriba sus comentarios aquí:"));
    commentsPanel.setPreferredSize(new java.awt.Dimension(356, 80));
    commentsPanel.setLayout(new java.awt.BorderLayout());

    commentsText.setColumns(20);
    commentsText.setRows(5);
    commentsScroll.setViewportView(commentsText);

    commentsPanel.add(commentsScroll, java.awt.BorderLayout.CENTER);

    commentsButton.setText("Enviar");
    commentsButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        commentsButtonActionPerformed(evt);
      }
    });
    commentsPanel.add(commentsButton, java.awt.BorderLayout.EAST);

    add(commentsPanel, java.awt.BorderLayout.PAGE_START);

    feedbackPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensajes de la applicación:"));
    feedbackPanel.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
    messagesScroll.setViewportView(feedbackPanel);

    add(messagesScroll, java.awt.BorderLayout.CENTER);

    settingsPanel.setPreferredSize(new java.awt.Dimension(700, 230));
    add(settingsPanel, java.awt.BorderLayout.PAGE_END);
  }// </editor-fold>//GEN-END:initComponents

  private void commentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsButtonActionPerformed
		// TODO add your handling code here:
		controller.onSendFeedback (null);
  }//GEN-LAST:event_commentsButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton commentsButton;
  private javax.swing.JPanel commentsPanel;
  private javax.swing.JScrollPane commentsScroll;
  private javax.swing.JTextArea commentsText;
  private javax.swing.JEditorPane feedbackPanel;
  private javax.swing.JScrollPane messagesScroll;
  private config.SettingsPanel settingsPanel;
  // End of variables declaration//GEN-END:variables
}
